services:
  - type: web
    name: s2dcms-backend
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.yzjkctbhvawzbdfsyidg.supabase.co:5432/postgres
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATA_REDIS_HOST
        value: vase-happy-stately-64039.db.redis.io
      - key: SPRING_DATA_REDIS_PORT
        value: "10837"
      - key: SPRING_DATA_REDIS_PASSWORD
        sync: false
      - key: SPRING_RABBITMQ_HOST
        value: cow.rmq2.cloudamqp.com
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
      - key: SPRING_RABBITMQ_USERNAME
        value: gmhikdiq
      - key: SPRING_RABBITMQ_PASSWORD
        sync: false
      - key: spring.ai.openai.api-key
        sync: false
