
# APPLICATION

spring.application.name=S2dcms


# DATASOURCE / POSTGRESQL

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/YOUR_DATABASE_NAME}
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:YOUR_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# HIBERNATE / JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Naming strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# FLYWAY

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.ignore-unsupported-migrations=true
spring.flyway.repair=true

logging.level.org.flywaydb=INFO


# SMTP (OPTIONAL LOCAL TESTING)

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false


# BREVO API CONFIG

brevo.api.key=YOUR_BREVO_API_KEY
brevo.sender.email=YOUR_EMAIL@example.com
brevo.sender.name=S2DCMS Support


# FRONTEND

frontend.base.url=http://localhost:5173


# JWT

jwt.secret=YOUR_SUPER_SECRET_KEY
jwt.access.expiration=900000
jwt.refresh.expiration=86400000


# FILE STORAGE

file.dir=attachments
file.max-size=20MB

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# RATE LIMITING

limit.max_attempt=4
limit.cooldown_minutes=60


# REDIS CACHE

spring.cache.type=redis

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Cache expires automatically after 10 minutes
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
spring.cache.redis.time-to-live=600000

# RABBITMQ CONFIGURATION
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=10

# CONTACT EMAIL
admin.email=YOUR_ADMIN_EMAIL@example.com

# GROQ AI CONFIGURATION
spring.ai.openai.api-key=YOUR_GROQ_API_KEY
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
spring.ai.openai.chat.options.temperature=0.7
